Seed: 42
Data:
    base_dir: "data/"
    train_batch_size: 128
    dropout: 0.2
    fusion: 1
    val_batch_size: 64
    test_batch_size: 64
    mode: 'one-hot'
    num_classes: 16

Calibration:
    label_smoothing: True
    smoothing_param: 0.1
    n_bins: 20
Optimization:
    lr: 0.0002
    lr_schedule:
        name: 'StepLR'
        step_size: 5
        decay: 0.5
    patience: 10

Logger:
    save_dir: "results/"

Trainer:
    max_epochs: 30

